name: NBA 3-Point Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      api_key:
        description: 'SportsData API Key (optional)'
        required: false
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci || npm install
      
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      
      - name: Run NBA 3-Point Test
        run: npm run test:ci
        env:
          API_KEY: ${{ github.event.inputs.api_key || secrets.SPORTSDATA_API_KEY }}
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: playwright-report/
          retention-days: 30 